apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fanloop.fullname" . }}-config
  labels:
    {{- include "fanloop.labels" . | nindent 4 }}
data:
  REDIS_HOST: {{ include "fanloop.redisHost" . | quote }}
  REDIS_PORT: "6379"
