apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fanloop.fullname" . }}
  labels:
    {{- include "fanloop.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fanloop.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fanloop.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 40
      containers:
        - name: fanloop
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: {{ include "fanloop.fullname" . }}-config
            - secretRef:
                name: {{ include "fanloop.fullname" . }}-secret
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
