apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fanloop.fullname" . }}-secret
  labels:
    {{- include "fanloop.labels" . | nindent 4 }}
type: Opaque
stringData:
  FANLOOP_API_KEY: {{ .Values.apiKey | quote }}
