{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "fanloop.fullname" . }}
  labels:
    {{- include "fanloop.labels" . | nindent 4 }}
    release: monitoring
spec:
  selector:
    matchLabels:
      {{- include "fanloop.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
